{% set name = "cni" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containernetworking/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 802f4a002b4eb774624a9dc1c859d3c9926eb2d862e66a673fc99cfc8bcd7494

build:
  skip: True  # [not linux]
  number: 1

requirements:
  build:
    - {{ compiler('go') }}
    - make
  host:
  run:
    - jq

test:
  commands:
    - which cnitool

about:
  home: https://github.com/containernetworking/cni
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: CNI is a specification and libraries for writing plugins to configure network interfaces in Linux containers.
  dev_url: https://github.com/containernetworking/cni

extra:
  recipe-maintainers:
    - sodre
