travis:
  secure:
    BINSTAR_TOKEN: Tr9ZN23Ygjp/N8d0uE4f1U4s4ZiDQm1DqMklFz668BePww9zQwixuyV8JBXkpYREUPFN8+nVdP7l+mEqrpBmZOviuphnTPvZVQ6mBgT+TlQ0FAXdOCXDewVFJEzvHtqUJFAYI0Qbwuc5E/2KV5i0CWTWI5UJS26/GFrfsAkKIq10kk2Smu8wpdlkYkvYsupHLncFEEI/dwXMAOiFRXqGRmm2fK9uYMoJqiIjqWgVhkiDbq25Jv4mkwu71GrDRJyuzSFcf8N17p/R6oJf6VL5K4x2g3kMH8/cpMeNBqOtmXneipl9W0D/mDrtA53Tl+X93rB62CHLLZvelOnT1OS4Y+8tqp/HQlsQcAoIOdI4X6uKtPciRyyxgwvXfUCEgKTc2+2AUbn+TeSIkeUdjKK4SPF6HhDQsJgtvasQWlf7ANKFimUP1qHkISM9eZ0gtxirLoxRYkFfDP0ZC5wv0wCSThmVYco7ICX4SdPcXv27Lh7Yr1ztwFqSAfIpnORiNFY39ZN6VOnktiLGu5B7Nzk0JdSE70GkAxa08iPw2+F222QO2ymobnpONzCvcrFHsV2QEetjXhqj7fGTreAahD041kRd+cjBzAdDVTW5keHf3x6AbiO0kN1JQF2FDW50Hfrk2CRf34V8HW+r4R3/65+lTk1q977J7PsnyDuFIOJ9usQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
