travis:
  secure:
    BINSTAR_TOKEN: GcrLdbhgB7kLrJ5itxVwoIY6JigCaxgTzlVZCriKLQgZcv115dAFPJ5V4lBverir02+vvvTlA2CYoSXAAwndXkweRjteR7IRJ9UbWs1HK8egwZLhyBrK5MV38nGKxTtKE2yU1A42qCmcEGuFg7SWRs2A+VU0PMEr046zU+71E2FHylflbKNW0LqC1Q5m60f4QbzBlUoXj4mraPpiGHK59smRu396K6AOG4XV2zSfwU0iJh6Q2rFpxWQzpasl997jrEAgRsUOW9/eBEUFAr7QfbbTRUHY0Cuwzh4gTwMb+rVRwRGqE96/mRCMLJiEhOwFBv47TleZl5LTK7be1YbJicAW/Ek9bj7LA7Chp+LoBZRPvk13t+kdEtA3iSOitf8UWtrvK1flT5slpdC3UHwqjtKm9Y8embRkoy92GbpYdg472Nb6kzsctDvUJd7WanVo26bg8bhTm5v8OdRTj8dWMcVR628UjyH9qn4uGyPsZLmQC2eYfA7MGzrrBzZ9wefT/ZD0W9zVOZwVDI/RrAwpOlZnN1/9PVKNc5H9GeA7pBFoIUkgeX6Q49uyoxKWobztxlSwAXzvQgMxOw+AcGEVMJmF7JbEzUM6W7yRi/NqY4x5FIsn/KCQY1jMx78GhR7a+QlOCx5JsXrpdsix/34vyQQ0xcdrUGkStUnx8y2/NtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
