travis:
  secure:
    BINSTAR_TOKEN: apFmVUhHEm5myi2ptlOHRZtpjxAZJMUfSc3LW+MR/pJwGsyGpWvjF5hKRrJO6coGzQMj79dAlJdqof6QWSOnR7504Xdk9EzXQrdqo3ABjaVziUkPnuHo/PHg5yFzJLpAzHQaFsokMq4BFZnUH0vJdmgb7/UXZWX23oNpaGo8+skYRCLKCPSF/r+9sAx6v1pEpt5BMGRSs5i4X6a3wnlTpqLpzXYKcuugiSluNjc0EXg7phWp8wEsmq8aRE3GzACK8eKi61i0kHhmkgHqcJdGSwVVwm/UwS0+uaOgeEIR4L2ecZw2F5MezZOwmdL/XAPtAIQdhopvkg5BnwLUgioM1uJNsAZeDqPCYzVNQ0fsYa4chz77Il9TKDQxKNEsoCGTc2TwE3G5hHZqopKbQ5yp6FkPo+VRq4cQjvnFpOFMCkubUbkdbkK9NwmkjA60YEm8cL0A4YXl9sG6IoepyhW6iudRu/2e5Hx73TGDVkSFQS40rHc+RODgb54KskO9l2hKzHGKdAhdttHEf/1j2yH35rr4nbsFLbkg05wuKt1Nl9dh9IHbp28VevO8MaOme+U1XRvRnmjPjE6TS13USatx+uocAveIPOaoUnfbEO5M5dLWjdBzZLVidsGKiR2BB0wLd+AKkiIKVPb9FuvrJapMZjF5u7BQqZ7c1jbEjCD4Q2E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
